// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/cuid/cuid.d.ts
declare module 'cuid' {
	function cuid(): string;
	
	export = cuid
}
